name: levite_hardware
description: "A Flutter POS system for hardware store management with SQLite database."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Database
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  
  # Charts for Analytics
  fl_chart: ^0.68.0
  
  # HTTP requests (if needed for future features)
  http: ^1.2.1
  
  # Date formatting
  intl: ^0.19.0
  
  # File operations
  path_provider: ^2.1.3
  
  # PDF generation for receipts
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Image handling
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets for product images and icons
  assets:
    - assets/images/
    - assets/icons/
  
  # Custom fonts for better UI
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
